<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Breadcrumb renders the full navigation trail.
-->
<script lang="ts" module>
  import type { BreadcrumbItem } from "./breadcrumb.shared";

  export type BreadcrumbProps = {
    items?: BreadcrumbItem[];
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { breadcrumbClasses } from "./breadcrumb.shared";
  import { cn } from "../../utils";
  import { isSetStr, orUndef } from "../../utils/expr";

  let {
    items,
    class: className,
    ...rest
  }: BreadcrumbProps = $props();

  const cls = $derived(breadcrumbClasses({ className }));
</script>

<nav {...(cls ? { class: cls } : {})} {...rest}>
  <ol class="flex flex-wrap items-center gap-2">
    {#each items ?? [] as item}
      <li class="inline-flex items-center">
        {#if (isSetStr(item.href) && !(item.disabled))}
          <a href={orUndef(item.href)} {...((cn("text-sm", (item.current ? "font-medium" : (item.disabled ? "text-muted-foreground" : "text-primary underline-offset-4 hover:underline")))) ? { class: cn("text-sm", (item.current ? "font-medium" : (item.disabled ? "text-muted-foreground" : "text-primary underline-offset-4 hover:underline"))) } : {})} aria-current={item.current ? "page" : undefined}>{item.label}</a>
        {:else}
          <span {...((cn("text-sm", (item.current ? "font-medium" : (item.disabled ? "text-muted-foreground" : "text-primary underline-offset-4 hover:underline")))) ? { class: cn("text-sm", (item.current ? "font-medium" : (item.disabled ? "text-muted-foreground" : "text-primary underline-offset-4 hover:underline"))) } : {})} aria-current={item.current ? "page" : undefined}>{item.label}</span>
        {/if}
      </li>
    {/each}
  </ol>
</nav>
