// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.breadcrumb — shared TypeScript contract (types + classes helpers)

import { cn } from "../../utils";

export type BreadcrumbItem = {
  label?: string;
  href?: string;
  current?: boolean;
  disabled?: boolean;
};

/** Breadcrumb renders the full navigation trail. */
export type BreadcrumbBaseProps = {
  items?: BreadcrumbItem[];
};

export type BreadcrumbClassesInput = {
  className?: string;
};

/** Compose Breadcrumb classes without rendering — the cross-runtime `asChild` substitute. */
export function breadcrumbClasses(input: BreadcrumbClassesInput = {}): string {
  return cn("text-sm", input.className);
}
