// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.box — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import boxRecipeJson from "./box.variants.json";

export const boxRecipe = boxRecipeJson;

/** Box renders a div layout wrapper. */
export type BoxBaseProps = {
  tag?: string;
};

export type BoxClassesInput = {
  className?: string;
};

/** Compose Box classes without rendering — the cross-runtime `asChild` substitute. */
export function boxClasses(input: BoxClassesInput = {}): string {
  return cn(composeRecipe(boxRecipe, {  }), input.className);
}
