<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Box renders a div layout wrapper.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type BoxProps = {
    tag?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { boxClasses } from "./box.shared";
  import { resolveTag, TagGroup } from "../../utils/tags";

  let {
    tag,
    class: className,
    children,
    ...rest
  }: BoxProps = $props();

  const cls = $derived(boxClasses({ className }));
  const resolvedTagValue = $derived(resolveTag(tag, "div", TagGroup.BoxAllowed));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
