<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Stack renders a vertical flex container.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type StackProps = {
    tag?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { stackClasses } from "./stack.shared";
  import { resolveTag, TagGroup } from "../../utils/tags";

  let {
    tag,
    class: className,
    children,
    ...rest
  }: StackProps = $props();

  const cls = $derived(stackClasses({ className }));
  const resolvedTagValue = $derived(resolveTag(tag, "div", TagGroup.Stack));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
