// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.stack — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import stackRecipeJson from "./stack.variants.json";

export const stackRecipe = stackRecipeJson;

/** Stack renders a vertical flex container. */
export type StackBaseProps = {
  tag?: string;
};

export type StackClassesInput = {
  className?: string;
};

/** Compose Stack classes without rendering — the cross-runtime `asChild` substitute. */
export function stackClasses(input: StackClassesInput = {}): string {
  return cn(composeRecipe(stackRecipe, {  }), input.className);
}
