<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Button renders a button element, or an anchor when Href is set.
  Type/Form apply only in button mode; Disabled on anchors uses aria-disabled.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { ButtonSize, ButtonVariant } from "./button.shared";

  export type ButtonProps = {
    variant?: ButtonVariant;
    size?: ButtonSize;
    type?: string;
    href?: string;
    target?: string;
    rel?: string;
    external?: boolean;
    disabled?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { buttonClasses } from "./button.shared";
  import { eqStr, isSetStr, oneOfOr, orUndef } from "../../utils/expr";

  let {
    variant,
    size,
    type,
    href,
    target,
    rel,
    external,
    disabled,
    class: className,
    children,
    ...rest
  }: ButtonProps = $props();

  const cls = $derived(buttonClasses({ variant, size, disabled, className }));
  const targetValue = $derived((isSetStr(target) ? target : (external ? "_blank" : "")));
  const relValue = $derived((isSetStr(rel) ? rel : ((external || eqStr(targetValue, "_blank")) ? "noopener noreferrer" : "")));
</script>

{#if isSetStr(href)}
  <a href={orUndef(href)} {...(cls ? { class: cls } : {})} target={orUndef(targetValue)} rel={orUndef(relValue)} aria-disabled={disabled ? "true" : undefined} tabindex={disabled ? -1 : undefined} {...rest}>
    {@render children?.()}
  </a>
{:else}
  <button type={oneOfOr(type, "button", "submit", "reset")} {...(cls ? { class: cls } : {})} disabled={disabled || undefined} {...rest}>
    {@render children?.()}
  </button>
{/if}
