// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.button — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import buttonRecipeJson from "./button.variants.json";

export const buttonRecipe = buttonRecipeJson;

export type ButtonVariant = RecipeKey<typeof buttonRecipe, "variant">;
export type ButtonSize = RecipeKey<typeof buttonRecipe, "size">;

/** Button renders a button element, or an anchor when Href is set. */
export type ButtonBaseProps = {
  variant?: ButtonVariant;
  size?: ButtonSize;
  type?: string;
  href?: string;
  target?: string;
  rel?: string;
  external?: boolean;
  disabled?: boolean;
};

export type ButtonClassesInput = {
  variant?: ButtonVariant;
  size?: ButtonSize;
  disabled?: boolean;
  className?: string;
};

/** Compose Button classes without rendering — the cross-runtime `asChild` substitute. */
export function buttonClasses(input: ButtonClassesInput = {}): string {
  return cn(composeRecipe(buttonRecipe, { variant: input.variant, size: input.size }), (input.disabled ? "pointer-events-none opacity-50" : ""), input.className);
}
