<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Switch renders input[type=checkbox] with switch role attrs.
-->
<script lang="ts" module>
  import type { SwitchSize, SwitchVariant } from "./switch.shared";

  export type SwitchProps = {
    variant?: SwitchVariant;
    size?: SwitchSize;
    checked?: boolean;
    disabled?: boolean;
    required?: boolean;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { switchClasses } from "./switch.shared";
  import { boolStr } from "../../utils/expr";

  let {
    variant,
    size,
    checked,
    disabled,
    required,
    class: className,
    ...rest
  }: SwitchProps = $props();

  const cls = $derived(switchClasses({ variant, size, className }));
</script>

<input type="checkbox" {...(cls ? { class: cls } : {})} checked={checked || undefined} disabled={disabled || undefined} required={required || undefined} role="switch" aria-checked={boolStr(checked)} {...rest} />
