// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.switch — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import switchRecipeJson from "./switch.variants.json";

export const switchRecipe = switchRecipeJson;

export type SwitchVariant = RecipeKey<typeof switchRecipe, "variant">;
export type SwitchSize = RecipeKey<typeof switchRecipe, "size">;

/** Switch renders input[type=checkbox] with switch role attrs. */
export type SwitchBaseProps = {
  variant?: SwitchVariant;
  size?: SwitchSize;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
};

export type SwitchClassesInput = {
  variant?: SwitchVariant;
  size?: SwitchSize;
  className?: string;
};

/** Compose Switch classes without rendering — the cross-runtime `asChild` substitute. */
export function switchClasses(input: SwitchClassesInput = {}): string {
  return cn(composeRecipe(switchRecipe, { variant: input.variant, size: input.size }), input.className);
}
