<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Text renders a p element with body copy classes.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TextProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { textClasses } from "./text.shared";

  let {
    class: className,
    children,
    ...rest
  }: TextProps = $props();

  const cls = $derived(textClasses({ className }));
</script>

<p {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</p>
