// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.text — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import textRecipeJson from "./text.variants.json";

export const textRecipe = textRecipeJson;

/** Text renders a p element with body copy classes. */
export type TextBaseProps = {

};

export type TextClassesInput = {
  className?: string;
};

/** Compose Text classes without rendering — the cross-runtime `asChild` substitute. */
export function textClasses(input: TextClassesInput = {}): string {
  return cn(composeRecipe(textRecipe, {  }), input.className);
}
