<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Break renders br by default, or wbr when Type is wbr/word.
-->
<script lang="ts" module>

  export type BreakProps = {
    type?: string;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { breakClasses } from "./linebreak.shared";
  import { mapOr } from "../../utils/expr";

  let {
    type,
    class: className,
    ...rest
  }: BreakProps = $props();

  const cls = $derived(breakClasses({ className }));
  const resolvedTagValue = $derived(mapOr(type, { "wbr": "wbr", "word": "wbr" }, "br"));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest} />
