// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.linebreak — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import linebreakRecipeJson from "./linebreak.variants.json";

export const linebreakRecipe = linebreakRecipeJson;

/** Break renders br by default, or wbr when Type is wbr/word. */
export type BreakBaseProps = {
  type?: string;
};

export type BreakClassesInput = {
  className?: string;
};

/** Compose Break classes without rendering — the cross-runtime `asChild` substitute. */
export function breakClasses(input: BreakClassesInput = {}): string {
  return cn(composeRecipe(linebreakRecipe, {  }), input.className);
}
