<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Dialog renders a native dialog element.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { DialogSize, DialogVariant } from "./dialog.shared";

  export type DialogProps = {
    variant?: DialogVariant;
    size?: DialogSize;
    open?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { dialogClasses } from "./dialog.shared";

  let {
    variant,
    size,
    open,
    class: className,
    children,
    ...rest
  }: DialogProps = $props();

  const cls = $derived(dialogClasses({ variant, size, className }));
</script>

<dialog {...(cls ? { class: cls } : {})} open={open || undefined} {...rest}>
  {@render children?.()}
</dialog>
