// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.dialog — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import dialogRecipeJson from "./dialog.variants.json";

export const dialogRecipe = dialogRecipeJson;

export type DialogVariant = RecipeKey<typeof dialogRecipe, "variant">;
export type DialogSize = RecipeKey<typeof dialogRecipe, "size">;

/** Dialog renders a native dialog element. */
export type DialogBaseProps = {
  variant?: DialogVariant;
  size?: DialogSize;
  open?: boolean;
};

export type DialogClassesInput = {
  variant?: DialogVariant;
  size?: DialogSize;
  className?: string;
};

/** Compose Dialog classes without rendering — the cross-runtime `asChild` substitute. */
export function dialogClasses(input: DialogClassesInput = {}): string {
  return cn(composeRecipe(dialogRecipe, { variant: input.variant, size: input.size }), input.className);
}
