<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  ListItem renders one li with optional value attribute.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type ListItemProps = {
    tag?: string;
    value?: number;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { listItemClasses } from "./list.shared";
  import { eqStr, isSetNum } from "../../utils/expr";
  import { resolveTag, TagGroup } from "../../utils/tags";

  let {
    tag,
    value,
    class: className,
    children,
    ...rest
  }: ListItemProps = $props();

  const cls = $derived(listItemClasses({ className }));
  const resolvedTagValue = $derived(resolveTag(tag, "li", TagGroup.ListItem));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} value={(isSetNum(value) && eqStr(resolvedTagValue, "li")) ? String(value ?? 0) : undefined} {...rest}>
  {@render children?.()}
</svelte:element>
