<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  List renders a list container (ul, ol, dl, or menu).
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type ListProps = {
    tag?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { listClasses } from "./list.shared";
  import { resolveTag, TagGroup } from "../../utils/tags";

  let {
    tag,
    class: className,
    children,
    ...rest
  }: ListProps = $props();

  const cls = $derived(listClasses({ className }));
  const resolvedTagValue = $derived(resolveTag(tag, "ul", TagGroup.List));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
