// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.list — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import listRecipeJson from "./list.variants.json";

export const listRecipe = listRecipeJson;

/** List renders a list container (ul, ol, dl, or menu). */
export type ListBaseProps = {
  tag?: string;
};

export type ListClassesInput = {
  className?: string;
};

/** Compose List classes without rendering — the cross-runtime `asChild` substitute. */
export function listClasses(input: ListClassesInput = {}): string {
  return cn(composeRecipe(listRecipe, {  }), input.className);
}

/** ListItem renders one li with optional value attribute. */
export type ListItemBaseProps = {
  tag?: string;
  value?: number;
};

export type ListItemClassesInput = {
  className?: string;
};

/** Compose ListItem classes without rendering — the cross-runtime `asChild` substitute. */
export function listItemClasses(input: ListItemClassesInput = {}): string {
  return cn(composeRecipe(listRecipe, {  }), input.className);
}
