// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.input — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import inputRecipeJson from "./input.variants.json";

export const inputRecipe = inputRecipeJson;

export type InputVariant = RecipeKey<typeof inputRecipe, "variant">;
export type InputSize = RecipeKey<typeof inputRecipe, "size">;

/** Input renders a styled single-line form control. */
export type InputBaseProps = {
  variant?: InputVariant;
  size?: InputSize;
  type?: string;
  disabled?: boolean;
  required?: boolean;
};

export type InputClassesInput = {
  variant?: InputVariant;
  size?: InputSize;
  className?: string;
};

/** Compose Input classes without rendering — the cross-runtime `asChild` substitute. */
export function inputClasses(input: InputClassesInput = {}): string {
  return cn(composeRecipe(inputRecipe, { variant: input.variant, size: input.size }), input.className);
}
