<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Input renders a styled single-line form control.
-->
<script lang="ts" module>
  import type { InputSize, InputVariant } from "./input.shared";

  export type InputProps = {
    variant?: InputVariant;
    size?: InputSize;
    type?: string;
    disabled?: boolean;
    required?: boolean;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { inputClasses } from "./input.shared";
  import { defaultIfEmpty } from "../../utils/expr";

  let {
    variant,
    size,
    type,
    disabled,
    required,
    class: className,
    ...rest
  }: InputProps = $props();

  const cls = $derived(inputClasses({ variant, size, className }));
</script>

<input type={defaultIfEmpty(type, "text")} {...(cls ? { class: cls } : {})} disabled={disabled || undefined} required={required || undefined} {...rest} />
