<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Disclosure renders native details.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { DisclosureSize, DisclosureVariant } from "./disclosure.shared";

  export type DisclosureProps = {
    variant?: DisclosureVariant;
    size?: DisclosureSize;
    open?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { disclosureClasses } from "./disclosure.shared";

  let {
    variant,
    size,
    open,
    class: className,
    children,
    ...rest
  }: DisclosureProps = $props();

  const cls = $derived(disclosureClasses({ variant, size, className }));
</script>

<details {...(cls ? { class: cls } : {})} open={open || undefined} {...rest}>
  {@render children?.()}
</details>
