// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.disclosure — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import disclosureRecipeJson from "./disclosure.variants.json";
import summaryRecipeJson from "./summary.variants.json";

export const disclosureRecipe = disclosureRecipeJson;
export const summaryRecipe = summaryRecipeJson;

export type DisclosureVariant = RecipeKey<typeof disclosureRecipe, "variant">;
export type DisclosureSize = RecipeKey<typeof disclosureRecipe, "size">;

/** Disclosure renders native details. */
export type DisclosureBaseProps = {
  variant?: DisclosureVariant;
  size?: DisclosureSize;
  open?: boolean;
};

export type DisclosureClassesInput = {
  variant?: DisclosureVariant;
  size?: DisclosureSize;
  className?: string;
};

/** Compose Disclosure classes without rendering — the cross-runtime `asChild` substitute. */
export function disclosureClasses(input: DisclosureClassesInput = {}): string {
  return cn(composeRecipe(disclosureRecipe, { variant: input.variant, size: input.size }), input.className);
}

export type SummaryVariant = RecipeKey<typeof summaryRecipe, "variant">;
export type SummarySize = RecipeKey<typeof summaryRecipe, "size">;

/** Summary renders native summary. */
export type SummaryBaseProps = {
  variant?: SummaryVariant;
  size?: SummarySize;
};

export type SummaryClassesInput = {
  variant?: SummaryVariant;
  size?: SummarySize;
  className?: string;
};

/** Compose Summary classes without rendering — the cross-runtime `asChild` substitute. */
export function summaryClasses(input: SummaryClassesInput = {}): string {
  return cn(composeRecipe(summaryRecipe, { variant: input.variant, size: input.size }), input.className);
}
