<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Summary renders native summary.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { SummarySize, SummaryVariant } from "./disclosure.shared";

  export type SummaryProps = {
    variant?: SummaryVariant;
    size?: SummarySize;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { summaryClasses } from "./disclosure.shared";

  let {
    variant,
    size,
    class: className,
    children,
    ...rest
  }: SummaryProps = $props();

  const cls = $derived(summaryClasses({ variant, size, className }));
</script>

<summary {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</summary>
