<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Label renders accessible text linked to a control.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type LabelProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { labelClasses } from "./label.shared";

  let {
    class: className,
    children,
    ...rest
  }: LabelProps = $props();

  const cls = $derived(labelClasses({ className }));
</script>

<label {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</label>
