// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.label — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import labelRecipeJson from "./label.variants.json";

export const labelRecipe = labelRecipeJson;

/** Label renders accessible text linked to a control. */
export type LabelBaseProps = {

};

export type LabelClassesInput = {
  className?: string;
};

/** Compose Label classes without rendering — the cross-runtime `asChild` substitute. */
export function labelClasses(input: LabelClassesInput = {}): string {
  return cn(composeRecipe(labelRecipe, {  }), input.className);
}
