<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableFoot renders the tfoot section.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableFootProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableFootClasses } from "./table.shared";

  let {
    class: className,
    children,
    ...rest
  }: TableFootProps = $props();

  const cls = $derived(tableFootClasses({ className }));
</script>

<tfoot {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</tfoot>
