<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableCell renders td with colspan and rowspan.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableCellProps = {
    scope?: string;
    colspan?: number;
    rowspan?: number;
    abbr?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableCellClasses } from "./table.shared";
  import { isSetNum } from "../../utils/expr";

  let {
    scope,
    colspan: colSpan,
    rowspan: rowSpan,
    abbr,
    class: className,
    children,
    ...rest
  }: TableCellProps = $props();

  const cls = $derived(tableCellClasses({ className }));
</script>

<td {...(cls ? { class: cls } : {})} colspan={isSetNum(colSpan) ? String(colSpan ?? 0) : undefined} rowspan={isSetNum(rowSpan) ? String(rowSpan ?? 0) : undefined} {...rest}>
  {@render children?.()}
</td>
