<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableColGroup renders colgroup with optional span.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableColGroupProps = {
    span?: number;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableColGroupClasses } from "./table.shared";
  import { isSetNum } from "../../utils/expr";

  let {
    span,
    class: className,
    children,
    ...rest
  }: TableColGroupProps = $props();

  const cls = $derived(tableColGroupClasses({ className }));
</script>

<colgroup {...(cls ? { class: cls } : {})} span={isSetNum(span) ? String(span ?? 0) : undefined} {...rest}>
  {@render children?.()}
</colgroup>
