<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableCol renders a single col definition.
-->
<script lang="ts" module>

  export type TableColProps = {
    span?: number;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableColClasses } from "./table.shared";
  import { isSetNum } from "../../utils/expr";

  let {
    span,
    class: className,
    ...rest
  }: TableColProps = $props();

  const cls = $derived(tableColClasses({ className }));
</script>

<col {...(cls ? { class: cls } : {})} span={isSetNum(span) ? String(span ?? 0) : undefined} {...rest} />
