<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableRow renders one tr row.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableRowProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableRowClasses } from "./table.shared";

  let {
    class: className,
    children,
    ...rest
  }: TableRowProps = $props();

  const cls = $derived(tableRowClasses({ className }));
</script>

<tr {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</tr>
