<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Table renders the root table element.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableClasses } from "./table.shared";

  let {
    class: className,
    children,
    ...rest
  }: TableProps = $props();

  const cls = $derived(tableClasses({ className }));
</script>

<table {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</table>
