<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableHead renders the thead section.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableHeadProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableHeadClasses } from "./table.shared";

  let {
    class: className,
    children,
    ...rest
  }: TableHeadProps = $props();

  const cls = $derived(tableHeadClasses({ className }));
</script>

<thead {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</thead>
