// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.table — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import tableRecipeJson from "./table.variants.json";

export const tableRecipe = tableRecipeJson;

/** Table renders the root table element. */
export type TableBaseProps = {

};

export type TableClassesInput = {
  className?: string;
};

/** Compose Table classes without rendering — the cross-runtime `asChild` substitute. */
export function tableClasses(input: TableClassesInput = {}): string {
  return cn(composeRecipe(tableRecipe, {  }), input.className);
}

/** TableCaption renders the table caption. */
export type TableCaptionBaseProps = {

};

export type TableCaptionClassesInput = {
  className?: string;
};

/** Compose TableCaption classes without rendering — the cross-runtime `asChild` substitute. */
export function tableCaptionClasses(input: TableCaptionClassesInput = {}): string {
  return cn(input.className);
}

/** TableHead renders the thead section. */
export type TableHeadBaseProps = {

};

export type TableHeadClassesInput = {
  className?: string;
};

/** Compose TableHead classes without rendering — the cross-runtime `asChild` substitute. */
export function tableHeadClasses(input: TableHeadClassesInput = {}): string {
  return cn(input.className);
}

/** TableBody renders the tbody section. */
export type TableBodyBaseProps = {

};

export type TableBodyClassesInput = {
  className?: string;
};

/** Compose TableBody classes without rendering — the cross-runtime `asChild` substitute. */
export function tableBodyClasses(input: TableBodyClassesInput = {}): string {
  return cn(input.className);
}

/** TableFoot renders the tfoot section. */
export type TableFootBaseProps = {

};

export type TableFootClassesInput = {
  className?: string;
};

/** Compose TableFoot classes without rendering — the cross-runtime `asChild` substitute. */
export function tableFootClasses(input: TableFootClassesInput = {}): string {
  return cn(input.className);
}

/** TableRow renders one tr row. */
export type TableRowBaseProps = {

};

export type TableRowClassesInput = {
  className?: string;
};

/** Compose TableRow classes without rendering — the cross-runtime `asChild` substitute. */
export function tableRowClasses(input: TableRowClassesInput = {}): string {
  return cn(input.className);
}

/** TableHeadCell renders th with optional scope and abbr. */
export type TableHeadCellBaseProps = {
  scope?: string;
  colSpan?: number;
  rowSpan?: number;
  abbr?: string;
};

export type TableHeadCellClassesInput = {
  className?: string;
};

/** Compose TableHeadCell classes without rendering — the cross-runtime `asChild` substitute. */
export function tableHeadCellClasses(input: TableHeadCellClassesInput = {}): string {
  return cn(input.className);
}

/** TableCell renders td with colspan and rowspan. */
export type TableCellBaseProps = {
  scope?: string;
  colSpan?: number;
  rowSpan?: number;
  abbr?: string;
};

export type TableCellClassesInput = {
  className?: string;
};

/** Compose TableCell classes without rendering — the cross-runtime `asChild` substitute. */
export function tableCellClasses(input: TableCellClassesInput = {}): string {
  return cn(input.className);
}

/** TableColGroup renders colgroup with optional span. */
export type TableColGroupBaseProps = {
  span?: number;
};

export type TableColGroupClassesInput = {
  className?: string;
};

/** Compose TableColGroup classes without rendering — the cross-runtime `asChild` substitute. */
export function tableColGroupClasses(input: TableColGroupClassesInput = {}): string {
  return cn(input.className);
}

/** TableCol renders a single col definition. */
export type TableColBaseProps = {
  span?: number;
};

export type TableColClassesInput = {
  className?: string;
};

/** Compose TableCol classes without rendering — the cross-runtime `asChild` substitute. */
export function tableColClasses(input: TableColClassesInput = {}): string {
  return cn(input.className);
}
