<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableCaption renders the table caption.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableCaptionProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableCaptionClasses } from "./table.shared";

  let {
    class: className,
    children,
    ...rest
  }: TableCaptionProps = $props();

  const cls = $derived(tableCaptionClasses({ className }));
</script>

<caption {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</caption>
