<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  TableBody renders the tbody section.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TableBodyProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { tableBodyClasses } from "./table.shared";

  let {
    class: className,
    children,
    ...rest
  }: TableBodyProps = $props();

  const cls = $derived(tableBodyClasses({ className }));
</script>

<tbody {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</tbody>
