<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Icon renders a class-based span, svg use, or text fallback host.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { IconSize } from "./icon.shared";

  export type IconProps = {
    name?: string;
    type?: string;
    baseClass?: string;
    prefix?: string;
    size?: IconSize;
    href?: string;
    title?: string;
    "aria-label"?: string;
    decorative?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { iconClasses } from "./icon.shared";
  import { eqStr, isSetStr, oneOfOr, orUndef } from "../../utils/expr";

  let {
    name,
    type,
    baseClass,
    prefix,
    size,
    href,
    title,
    "aria-label": ariaLabel,
    decorative,
    class: className,
    children,
    ...rest
  }: IconProps = $props();

  const cls = $derived(iconClasses({ type, size, baseClass, name, prefix, className }));
  const iconKindValue = $derived(oneOfOr(type, "class", "svg", "text"));
  const isDecorativeValue = $derived((decorative || (!(isSetStr(title)) && !(isSetStr(ariaLabel)))));
</script>

{#if eqStr(iconKindValue, "svg")}
  <svg {...(cls ? { class: cls } : {})} aria-hidden={isDecorativeValue ? "true" : undefined} role={!(isDecorativeValue) ? "img" : undefined} aria-label={(!(isDecorativeValue) && isSetStr(ariaLabel)) ? ariaLabel : undefined} {...rest}>
    {#if isSetStr(title)}
      <title>{title}</title>
    {/if}
    {#if isSetStr(href)}
      <use href={orUndef(href)}></use>
    {/if}
    {@render children?.()}
  </svg>
{:else if eqStr(iconKindValue, "text")}
  <span {...(cls ? { class: cls } : {})} aria-hidden={isDecorativeValue ? "true" : undefined} role={!(isDecorativeValue) ? "img" : undefined} aria-label={(!(isDecorativeValue) && isSetStr(ariaLabel)) ? ariaLabel : undefined} {...rest}>
    {@render children?.()}
  </span>
{:else}
  <span {...(cls ? { class: cls } : {})} aria-hidden={isDecorativeValue ? "true" : undefined} role={!(isDecorativeValue) ? "img" : undefined} aria-label={(!(isDecorativeValue) && isSetStr(ariaLabel)) ? ariaLabel : undefined} {...rest}></span>
{/if}
