// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.iconbadge — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import iconbadgeRecipeJson from "./iconbadge.variants.json";

export const iconbadgeRecipe = iconbadgeRecipeJson;

export type IconBadgeVariant = RecipeKey<typeof iconbadgeRecipe, "variant">;
export type IconBadgeSize = RecipeKey<typeof iconbadgeRecipe, "size">;

/** IconBadge renders children as the badge content. */
export type IconBadgeBaseProps = {
  variant?: IconBadgeVariant;
  size?: IconBadgeSize;
};

export type IconBadgeClassesInput = {
  variant?: IconBadgeVariant;
  size?: IconBadgeSize;
  className?: string;
};

/** Compose IconBadge classes without rendering — the cross-runtime `asChild` substitute. */
export function iconBadgeClasses(input: IconBadgeClassesInput = {}): string {
  return cn(composeRecipe(iconbadgeRecipe, { variant: input.variant, size: input.size }), input.className);
}
