<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  IconBadge renders children as the badge content.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { IconBadgeSize, IconBadgeVariant } from "./iconbadge.shared";

  export type IconBadgeProps = {
    variant?: IconBadgeVariant;
    size?: IconBadgeSize;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { iconBadgeClasses } from "./iconbadge.shared";

  let {
    variant,
    size,
    class: className,
    children,
    ...rest
  }: IconBadgeProps = $props();

  const cls = $derived(iconBadgeClasses({ variant, size, className }));
</script>

<span {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</span>
