<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Textarea renders a styled multi-line form control.
-->
<script lang="ts" module>
  import type { TextareaSize, TextareaVariant } from "./textarea.shared";

  export type TextareaProps = {
    variant?: TextareaVariant;
    size?: TextareaSize;
    value?: string;
    rows?: number;
    disabled?: boolean;
    required?: boolean;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { textareaClasses } from "./textarea.shared";
  import { isSetNum } from "../../utils/expr";

  let {
    variant,
    size,
    value,
    rows,
    disabled,
    required,
    class: className,
    ...rest
  }: TextareaProps = $props();

  const cls = $derived(textareaClasses({ variant, size, className }));
</script>

<textarea {...(cls ? { class: cls } : {})} rows={(isSetNum(rows) ? String(rows ?? 0) : "4")} disabled={disabled || undefined} required={required || undefined} {...rest}>{value}</textarea>
