// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.textarea — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import textareaRecipeJson from "./textarea.variants.json";

export const textareaRecipe = textareaRecipeJson;

export type TextareaVariant = RecipeKey<typeof textareaRecipe, "variant">;
export type TextareaSize = RecipeKey<typeof textareaRecipe, "size">;

/** Textarea renders a styled multi-line form control. */
export type TextareaBaseProps = {
  variant?: TextareaVariant;
  size?: TextareaSize;
  value?: string;
  rows?: number;
  disabled?: boolean;
  required?: boolean;
};

export type TextareaClassesInput = {
  variant?: TextareaVariant;
  size?: TextareaSize;
  className?: string;
};

/** Compose Textarea classes without rendering — the cross-runtime `asChild` substitute. */
export function textareaClasses(input: TextareaClassesInput = {}): string {
  return cn(composeRecipe(textareaRecipe, { variant: input.variant, size: input.size }), input.className);
}
