<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Radio renders input[type=radio] with shared Name for grouping.
-->
<script lang="ts" module>
  import type { RadioSize, RadioVariant } from "./radio.shared";

  export type RadioProps = {
    variant?: RadioVariant;
    size?: RadioSize;
    checked?: boolean;
    disabled?: boolean;
    required?: boolean;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { radioClasses } from "./radio.shared";

  let {
    variant,
    size,
    checked,
    disabled,
    required,
    class: className,
    ...rest
  }: RadioProps = $props();

  const cls = $derived(radioClasses({ variant, size, className }));
</script>

<input type="radio" {...(cls ? { class: cls } : {})} checked={checked || undefined} disabled={disabled || undefined} required={required || undefined} {...rest} />
