// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.radio — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import radioRecipeJson from "./radio.variants.json";

export const radioRecipe = radioRecipeJson;

export type RadioVariant = RecipeKey<typeof radioRecipe, "variant">;
export type RadioSize = RecipeKey<typeof radioRecipe, "size">;

/** Radio renders input[type=radio] with shared Name for grouping. */
export type RadioBaseProps = {
  variant?: RadioVariant;
  size?: RadioSize;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
};

export type RadioClassesInput = {
  variant?: RadioVariant;
  size?: RadioSize;
  className?: string;
};

/** Compose Radio classes without rendering — the cross-runtime `asChild` substitute. */
export function radioClasses(input: RadioClassesInput = {}): string {
  return cn(composeRecipe(radioRecipe, { variant: input.variant, size: input.size }), input.className);
}
