<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  CardContent renders the padded main body slot.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type CardContentProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { cardContentClasses } from "./card.shared";

  let {
    class: className,
    children,
    ...rest
  }: CardContentProps = $props();

  const cls = $derived(cardContentClasses({ className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
