<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  CardFooter renders the bottom action slot with top border.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type CardFooterProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { cardFooterClasses } from "./card.shared";

  let {
    class: className,
    children,
    ...rest
  }: CardFooterProps = $props();

  const cls = $derived(cardFooterClasses({ className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
