<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Card renders the bordered surface wrapper.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { CardVariant } from "./card.shared";

  export type CardProps = {
    variant?: CardVariant;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { cardClasses } from "./card.shared";

  let {
    variant,
    class: className,
    children,
    ...rest
  }: CardProps = $props();

  const cls = $derived(cardClasses({ variant, className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
