<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  CardTitle renders heading text at the As level (default h2).
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type CardTitleProps = {
    as?: 1 | 2 | 3 | 4 | 5 | 6;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { cardTitleClasses } from "./card.shared";
  import { titleTag } from "../../utils/expr";

  let {
    as,
    class: className,
    children,
    ...rest
  }: CardTitleProps = $props();

  const cls = $derived(cardTitleClasses({ className }));
  const resolvedTagValue = $derived(titleTag(as));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
