// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.card — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import cardRecipeJson from "./card.variants.json";

export const cardRecipe = cardRecipeJson;

export type CardVariant = RecipeKey<typeof cardRecipe, "variant">;

/** Card renders the bordered surface wrapper. */
export type CardBaseProps = {
  variant?: CardVariant;
};

export type CardClassesInput = {
  variant?: CardVariant;
  className?: string;
};

/** Compose Card classes without rendering — the cross-runtime `asChild` substitute. */
export function cardClasses(input: CardClassesInput = {}): string {
  return cn(composeRecipe(cardRecipe, { variant: input.variant }), input.className);
}

/** CardHeader renders the top slot with bottom border. */
export type CardHeaderBaseProps = {

};

export type CardHeaderClassesInput = {
  className?: string;
};

/** Compose CardHeader classes without rendering — the cross-runtime `asChild` substitute. */
export function cardHeaderClasses(input: CardHeaderClassesInput = {}): string {
  return cn("border-b border-border px-4 py-2", input.className);
}

/** CardTitle renders heading text at the As level (default h2). */
export type CardTitleBaseProps = {
  as?: 1 | 2 | 3 | 4 | 5 | 6;
};

export type CardTitleClassesInput = {
  className?: string;
};

/** Compose CardTitle classes without rendering — the cross-runtime `asChild` substitute. */
export function cardTitleClasses(input: CardTitleClassesInput = {}): string {
  return cn("text-sm font-semibold", input.className);
}

/** CardDescription renders a muted subtitle in a p element. */
export type CardDescriptionBaseProps = {

};

export type CardDescriptionClassesInput = {
  className?: string;
};

/** Compose CardDescription classes without rendering — the cross-runtime `asChild` substitute. */
export function cardDescriptionClasses(input: CardDescriptionClassesInput = {}): string {
  return cn("text-sm text-muted-foreground", input.className);
}

/** CardContent renders the padded main body slot. */
export type CardContentBaseProps = {

};

export type CardContentClassesInput = {
  className?: string;
};

/** Compose CardContent classes without rendering — the cross-runtime `asChild` substitute. */
export function cardContentClasses(input: CardContentClassesInput = {}): string {
  return cn("p-4", input.className);
}

/** CardFooter renders the bottom action slot with top border. */
export type CardFooterBaseProps = {

};

export type CardFooterClassesInput = {
  className?: string;
};

/** Compose CardFooter classes without rendering — the cross-runtime `asChild` substitute. */
export function cardFooterClasses(input: CardFooterClassesInput = {}): string {
  return cn("border-t border-border px-4 py-3", input.className);
}
