<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  CardHeader renders the top slot with bottom border.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type CardHeaderProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { cardHeaderClasses } from "./card.shared";

  let {
    class: className,
    children,
    ...rest
  }: CardHeaderProps = $props();

  const cls = $derived(cardHeaderClasses({ className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
