<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  CardDescription renders a muted subtitle in a p element.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type CardDescriptionProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { cardDescriptionClasses } from "./card.shared";

  let {
    class: className,
    children,
    ...rest
  }: CardDescriptionProps = $props();

  const cls = $derived(cardDescriptionClasses({ className }));
</script>

<p {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</p>
