// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.inline — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import inlineRecipeJson from "./inline.variants.json";

export const inlineRecipe = inlineRecipeJson;

/** Inline renders a span element with inline copy classes. */
export type InlineBaseProps = {

};

export type InlineClassesInput = {
  className?: string;
};

/** Compose Inline classes without rendering — the cross-runtime `asChild` substitute. */
export function inlineClasses(input: InlineClassesInput = {}): string {
  return cn(composeRecipe(inlineRecipe, {  }), input.className);
}
