<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Inline renders a span element with inline copy classes.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type InlineProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { inlineClasses } from "./inline.shared";

  let {
    class: className,
    children,
    ...rest
  }: InlineProps = $props();

  const cls = $derived(inlineClasses({ className }));
</script>

<span {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</span>
