// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.badge — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import badgeRecipeJson from "./badge.variants.json";

export const badgeRecipe = badgeRecipeJson;

export type BadgeVariant = RecipeKey<typeof badgeRecipe, "variant">;
export type BadgeSize = RecipeKey<typeof badgeRecipe, "size">;

/** Badge renders label text in a div wrapper. */
export type BadgeBaseProps = {
  variant?: BadgeVariant;
  size?: BadgeSize;
};

export type BadgeClassesInput = {
  variant?: BadgeVariant;
  size?: BadgeSize;
  className?: string;
};

/** Compose Badge classes without rendering — the cross-runtime `asChild` substitute. */
export function badgeClasses(input: BadgeClassesInput = {}): string {
  return cn(composeRecipe(badgeRecipe, { variant: input.variant, size: input.size }), input.className);
}
