<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Badge renders label text in a div wrapper.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { BadgeSize, BadgeVariant } from "./badge.shared";

  export type BadgeProps = {
    variant?: BadgeVariant;
    size?: BadgeSize;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { badgeClasses } from "./badge.shared";

  let {
    variant,
    size,
    class: className,
    children,
    ...rest
  }: BadgeProps = $props();

  const cls = $derived(badgeClasses({ variant, size, className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
