// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.link — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import linkRecipeJson from "./link.variants.json";

export const linkRecipe = linkRecipeJson;

export type LinkVariant = RecipeKey<typeof linkRecipe, "variant">;
export type LinkSize = RecipeKey<typeof linkRecipe, "size">;

/** Link renders a semantic anchor element. */
export type LinkBaseProps = {
  variant?: LinkVariant;
  size?: LinkSize;
  target?: string;
  rel?: string;
  external?: boolean;
  disabled?: boolean;
};

export type LinkClassesInput = {
  variant?: LinkVariant;
  size?: LinkSize;
  disabled?: boolean;
  className?: string;
};

/** Compose Link classes without rendering — the cross-runtime `asChild` substitute. */
export function linkClasses(input: LinkClassesInput = {}): string {
  return cn(composeRecipe(linkRecipe, { variant: input.variant, size: input.size }), (input.disabled ? "pointer-events-none opacity-50" : ""), input.className);
}
