<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  OptGroup renders a native optgroup around option children.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type OptGroupProps = {
    disabled?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { optGroupClasses } from "./select.shared";

  let {
    disabled,
    class: className,
    children,
    ...rest
  }: OptGroupProps = $props();

  const cls = $derived(optGroupClasses({ className }));
</script>

<optgroup {...(cls ? { class: cls } : {})} disabled={disabled || undefined} {...rest}>
  {@render children?.()}
</optgroup>
