// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.select — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import selectRecipeJson from "./select.variants.json";

export const selectRecipe = selectRecipeJson;

export type SelectOptionItem = {
  value?: string;
  label?: string;
};

export type SelectVariant = RecipeKey<typeof selectRecipe, "variant">;
export type SelectSize = RecipeKey<typeof selectRecipe, "size">;

/** Select renders option children from the Options list plus manual children. */
export type SelectBaseProps = {
  variant?: SelectVariant;
  size?: SelectSize;
  value?: string;
  disabled?: boolean;
  required?: boolean;
  options?: SelectOptionItem[];
};

export type SelectClassesInput = {
  variant?: SelectVariant;
  size?: SelectSize;
  className?: string;
};

/** Compose Select classes without rendering — the cross-runtime `asChild` substitute. */
export function selectClasses(input: SelectClassesInput = {}): string {
  return cn(composeRecipe(selectRecipe, { variant: input.variant, size: input.size }), input.className);
}

/** SelectOption renders an option for custom Select children. */
export type SelectOptionBaseProps = {
  selected?: boolean;
  disabled?: boolean;
};

/** OptGroup renders a native optgroup around option children. */
export type OptGroupBaseProps = {
  disabled?: boolean;
};

export type OptGroupClassesInput = {
  className?: string;
};

/** Compose OptGroup classes without rendering — the cross-runtime `asChild` substitute. */
export function optGroupClasses(input: OptGroupClassesInput = {}): string {
  return cn(input.className);
}
