<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Select renders option children from the Options list plus manual children.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { SelectOptionItem, SelectSize, SelectVariant } from "./select.shared";

  export type SelectProps = {
    variant?: SelectVariant;
    size?: SelectSize;
    value?: string;
    disabled?: boolean;
    required?: boolean;
    options?: SelectOptionItem[];
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { selectClasses } from "./select.shared";
  import { eqStr } from "../../utils/expr";

  let {
    variant,
    size,
    value,
    disabled,
    required,
    options,
    class: className,
    children,
    ...rest
  }: SelectProps = $props();

  const cls = $derived(selectClasses({ variant, size, className }));
</script>

<select {...(cls ? { class: cls } : {})} disabled={disabled || undefined} required={required || undefined} {...rest}>
  {#each options ?? [] as item}
    <option value={(item.value) ?? ""} selected={eqStr(item.value, value) || undefined}>{item.label}</option>
  {/each}
  {@render children?.()}
</select>
