<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  SelectOption renders an option for custom Select children.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type SelectOptionProps = {
    selected?: boolean;
    disabled?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  let {
    selected,
    disabled,
    class: className,
    children,
    ...rest
  }: SelectOptionProps = $props();
</script>

<option selected={selected || undefined} disabled={disabled || undefined} {...rest}>
  {@render children?.()}
</option>
