// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.alert — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import alertRecipeJson from "./alert.variants.json";

export const alertRecipe = alertRecipeJson;

export type AlertVariant = RecipeKey<typeof alertRecipe, "variant">;

/** Alert renders a div with alert or status semantics. */
export type AlertBaseProps = {
  variant?: AlertVariant;
  role?: "status" | "alert";
  ariaLive?: "off" | "polite" | "assertive";
};

export type AlertClassesInput = {
  variant?: AlertVariant;
  className?: string;
};

/** Compose Alert classes without rendering — the cross-runtime `asChild` substitute. */
export function alertClasses(input: AlertClassesInput = {}): string {
  return cn(composeRecipe(alertRecipe, { variant: input.variant }), input.className);
}
