<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Alert renders a div with alert or status semantics.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { AlertVariant } from "./alert.shared";

  export type AlertProps = {
    variant?: AlertVariant;
    role?: "status" | "alert";
    "aria-live"?: "off" | "polite" | "assertive";
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { alertClasses } from "./alert.shared";
  import { defaultIfEmpty, oneOfOr } from "../../utils/expr";

  let {
    variant,
    role,
    "aria-live": ariaLive,
    class: className,
    children,
    ...rest
  }: AlertProps = $props();

  const cls = $derived(alertClasses({ variant, className }));
</script>

<div {...(cls ? { class: cls } : {})} role={oneOfOr(role, "status", "status", "alert")} aria-live={defaultIfEmpty(ariaLive, "polite")} {...rest}>
  {@render children?.()}
</div>
