// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.checkbox — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import checkboxRecipeJson from "./checkbox.variants.json";

export const checkboxRecipe = checkboxRecipeJson;

export type CheckboxVariant = RecipeKey<typeof checkboxRecipe, "variant">;
export type CheckboxSize = RecipeKey<typeof checkboxRecipe, "size">;

/** Checkbox renders a styled input[type=checkbox]. */
export type CheckboxBaseProps = {
  variant?: CheckboxVariant;
  size?: CheckboxSize;
  checked?: boolean;
  disabled?: boolean;
  required?: boolean;
};

export type CheckboxClassesInput = {
  variant?: CheckboxVariant;
  size?: CheckboxSize;
  className?: string;
};

/** Compose Checkbox classes without rendering — the cross-runtime `asChild` substitute. */
export function checkboxClasses(input: CheckboxClassesInput = {}): string {
  return cn(composeRecipe(checkboxRecipe, { variant: input.variant, size: input.size }), input.className);
}
