<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Checkbox renders a styled input[type=checkbox].
-->
<script lang="ts" module>
  import type { CheckboxSize, CheckboxVariant } from "./checkbox.shared";

  export type CheckboxProps = {
    variant?: CheckboxVariant;
    size?: CheckboxSize;
    checked?: boolean;
    disabled?: boolean;
    required?: boolean;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { checkboxClasses } from "./checkbox.shared";

  let {
    variant,
    size,
    checked,
    disabled,
    required,
    class: className,
    ...rest
  }: CheckboxProps = $props();

  const cls = $derived(checkboxClasses({ variant, size, className }));
</script>

<input type="checkbox" {...(cls ? { class: cls } : {})} checked={checked || undefined} disabled={disabled || undefined} required={required || undefined} {...rest} />
