// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.form.controls — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import fieldsetRecipeJson from "./fieldset.variants.json";
import legendRecipeJson from "./legend.variants.json";
import meterRecipeJson from "./meter.variants.json";
import progressRecipeJson from "./progress.variants.json";

export const fieldsetRecipe = fieldsetRecipeJson;
export const legendRecipe = legendRecipeJson;
export const meterRecipe = meterRecipeJson;
export const progressRecipe = progressRecipeJson;

export type FieldsetVariant = RecipeKey<typeof fieldsetRecipe, "variant">;
export type FieldsetSize = RecipeKey<typeof fieldsetRecipe, "size">;

/** Fieldset renders a native fieldset. */
export type FieldsetBaseProps = {
  variant?: FieldsetVariant;
  size?: FieldsetSize;
  disabled?: boolean;
};

export type FieldsetClassesInput = {
  variant?: FieldsetVariant;
  size?: FieldsetSize;
  className?: string;
};

/** Compose Fieldset classes without rendering — the cross-runtime `asChild` substitute. */
export function fieldsetClasses(input: FieldsetClassesInput = {}): string {
  return cn(composeRecipe(fieldsetRecipe, { variant: input.variant, size: input.size }), input.className);
}

export type LegendVariant = RecipeKey<typeof legendRecipe, "variant">;
export type LegendSize = RecipeKey<typeof legendRecipe, "size">;

/** Legend renders a native legend. */
export type LegendBaseProps = {
  variant?: LegendVariant;
  size?: LegendSize;
};

export type LegendClassesInput = {
  variant?: LegendVariant;
  size?: LegendSize;
  className?: string;
};

/** Compose Legend classes without rendering — the cross-runtime `asChild` substitute. */
export function legendClasses(input: LegendClassesInput = {}): string {
  return cn(composeRecipe(legendRecipe, { variant: input.variant, size: input.size }), input.className);
}

/** DataList renders a native datalist. */
export type DataListBaseProps = {

};

export type DataListClassesInput = {
  className?: string;
};

/** Compose DataList classes without rendering — the cross-runtime `asChild` substitute. */
export function dataListClasses(input: DataListClassesInput = {}): string {
  return cn(input.className);
}

/** DataOption renders an option inside a datalist. */
export type DataOptionBaseProps = {

};

/** Output renders a native output element. */
export type OutputBaseProps = {
  value?: string;
};

export type OutputClassesInput = {
  className?: string;
};

/** Compose Output classes without rendering — the cross-runtime `asChild` substitute. */
export function outputClasses(input: OutputClassesInput = {}): string {
  return cn(input.className);
}

export type MeterVariant = RecipeKey<typeof meterRecipe, "variant">;
export type MeterSize = RecipeKey<typeof meterRecipe, "size">;

/** Meter renders a native meter. */
export type MeterBaseProps = {
  variant?: MeterVariant;
  size?: MeterSize;
};

export type MeterClassesInput = {
  variant?: MeterVariant;
  size?: MeterSize;
  className?: string;
};

/** Compose Meter classes without rendering — the cross-runtime `asChild` substitute. */
export function meterClasses(input: MeterClassesInput = {}): string {
  return cn(composeRecipe(meterRecipe, { variant: input.variant, size: input.size }), input.className);
}

export type ProgressVariant = RecipeKey<typeof progressRecipe, "variant">;
export type ProgressSize = RecipeKey<typeof progressRecipe, "size">;

/** Progress renders a native progress element. */
export type ProgressBaseProps = {
  variant?: ProgressVariant;
  size?: ProgressSize;
};

export type ProgressClassesInput = {
  variant?: ProgressVariant;
  size?: ProgressSize;
  className?: string;
};

/** Compose Progress classes without rendering — the cross-runtime `asChild` substitute. */
export function progressClasses(input: ProgressClassesInput = {}): string {
  return cn(composeRecipe(progressRecipe, { variant: input.variant, size: input.size }), input.className);
}
