<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  DataList renders a native datalist.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type DataListProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { dataListClasses } from "./controls.shared";

  let {
    class: className,
    children,
    ...rest
  }: DataListProps = $props();

  const cls = $derived(dataListClasses({ className }));
</script>

<datalist {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</datalist>
