<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  DataOption renders an option inside a datalist.
-->
<script lang="ts" module>

  export type DataOptionProps = {
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  let {
    class: className,
    ...rest
  }: DataOptionProps = $props();
</script>

<option {...rest}></option>
