<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Fieldset renders a native fieldset.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { FieldsetSize, FieldsetVariant } from "./controls.shared";

  export type FieldsetProps = {
    variant?: FieldsetVariant;
    size?: FieldsetSize;
    disabled?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { fieldsetClasses } from "./controls.shared";

  let {
    variant,
    size,
    disabled,
    class: className,
    children,
    ...rest
  }: FieldsetProps = $props();

  const cls = $derived(fieldsetClasses({ variant, size, className }));
</script>

<fieldset {...(cls ? { class: cls } : {})} disabled={disabled || undefined} {...rest}>
  {@render children?.()}
</fieldset>
