<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  FormMessage renders destructive validation feedback.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type FormMessageProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { formMessageClasses } from "./form.shared";

  let {
    class: className,
    children,
    ...rest
  }: FormMessageProps = $props();

  const cls = $derived(formMessageClasses({ className }));
</script>

<p {...(cls ? { class: cls } : {})} role="alert" {...rest}>
  {@render children?.()}
</p>
