<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  FormItem groups a single field with spacing for label and control.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type FormItemProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { formItemClasses } from "./form.shared";

  let {
    class: className,
    children,
    ...rest
  }: FormItemProps = $props();

  const cls = $derived(formItemClasses({ className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
