<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  FormDescription renders muted helper copy below a control.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type FormDescriptionProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { formDescriptionClasses } from "./form.shared";

  let {
    class: className,
    children,
    ...rest
  }: FormDescriptionProps = $props();

  const cls = $derived(formDescriptionClasses({ className }));
</script>

<p {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</p>
