// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.form — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import formRecipeJson from "./form.variants.json";
import formItemRecipeJson from "./form-item.variants.json";
import formDescriptionRecipeJson from "./form-description.variants.json";
import formMessageRecipeJson from "./form-message.variants.json";

export const formRecipe = formRecipeJson;
export const formItemRecipe = formItemRecipeJson;
export const formDescriptionRecipe = formDescriptionRecipeJson;
export const formMessageRecipe = formMessageRecipeJson;

/** Form renders a vertical grid form container. */
export type FormBaseProps = {
  noValidate?: boolean;
};

export type FormClassesInput = {
  className?: string;
};

/** Compose Form classes without rendering — the cross-runtime `asChild` substitute. */
export function formClasses(input: FormClassesInput = {}): string {
  return cn(composeRecipe(formRecipe, {  }), input.className);
}

/** FormItem groups a single field with spacing for label and control. */
export type FormItemBaseProps = {

};

export type FormItemClassesInput = {
  className?: string;
};

/** Compose FormItem classes without rendering — the cross-runtime `asChild` substitute. */
export function formItemClasses(input: FormItemClassesInput = {}): string {
  return cn(composeRecipe(formItemRecipe, {  }), input.className);
}

/** FormDescription renders muted helper copy below a control. */
export type FormDescriptionBaseProps = {

};

export type FormDescriptionClassesInput = {
  className?: string;
};

/** Compose FormDescription classes without rendering — the cross-runtime `asChild` substitute. */
export function formDescriptionClasses(input: FormDescriptionClassesInput = {}): string {
  return cn(composeRecipe(formDescriptionRecipe, {  }), input.className);
}

/** FormMessage renders destructive validation feedback. */
export type FormMessageBaseProps = {

};

export type FormMessageClassesInput = {
  className?: string;
};

/** Compose FormMessage classes without rendering — the cross-runtime `asChild` substitute. */
export function formMessageClasses(input: FormMessageClassesInput = {}): string {
  return cn(composeRecipe(formMessageRecipe, {  }), input.className);
}
