<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Form renders a vertical grid form container.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type FormProps = {
    novalidate?: boolean;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { formClasses } from "./form.shared";

  let {
    novalidate: noValidate,
    class: className,
    children,
    ...rest
  }: FormProps = $props();

  const cls = $derived(formClasses({ className }));
</script>

<form {...(cls ? { class: cls } : {})} novalidate={noValidate || undefined} {...rest}>
  {@render children?.()}
</form>
