<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Legend renders a native legend.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { LegendSize, LegendVariant } from "./controls.shared";

  export type LegendProps = {
    variant?: LegendVariant;
    size?: LegendSize;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { legendClasses } from "./controls.shared";

  let {
    variant,
    size,
    class: className,
    children,
    ...rest
  }: LegendProps = $props();

  const cls = $derived(legendClasses({ variant, size, className }));
</script>

<legend {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</legend>
