<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Meter renders a native meter.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { MeterSize, MeterVariant } from "./controls.shared";

  export type MeterProps = {
    variant?: MeterVariant;
    size?: MeterSize;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { meterClasses } from "./controls.shared";

  let {
    variant,
    size,
    class: className,
    children,
    ...rest
  }: MeterProps = $props();

  const cls = $derived(meterClasses({ variant, size, className }));
</script>

<meter {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</meter>
