<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Output renders a native output element.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type OutputProps = {
    value?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { outputClasses } from "./controls.shared";

  let {
    value,
    class: className,
    children,
    ...rest
  }: OutputProps = $props();

  const cls = $derived(outputClasses({ className }));
</script>

<output {...(cls ? { class: cls } : {})} {...rest}>{value}{@render children?.()}</output>
