<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Progress renders a native progress element.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";
  import type { ProgressSize, ProgressVariant } from "./controls.shared";

  export type ProgressProps = {
    variant?: ProgressVariant;
    size?: ProgressSize;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { progressClasses } from "./controls.shared";

  let {
    variant,
    size,
    class: className,
    children,
    ...rest
  }: ProgressProps = $props();

  const cls = $derived(progressClasses({ variant, size, className }));
</script>

<progress {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</progress>
