// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.container — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import containerRecipeJson from "./container.variants.json";

export const containerRecipe = containerRecipeJson;

/** Container renders the outer content shell. */
export type ContainerBaseProps = {
  tag?: string;
};

export type ContainerClassesInput = {
  className?: string;
};

/** Compose Container classes without rendering — the cross-runtime `asChild` substitute. */
export function containerClasses(input: ContainerClassesInput = {}): string {
  return cn(composeRecipe(containerRecipe, {  }), input.className);
}
