<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Container renders the outer content shell.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type ContainerProps = {
    tag?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { containerClasses } from "./container.shared";
  import { resolveTag, TagGroup } from "../../utils/tags";

  let {
    tag,
    class: className,
    children,
    ...rest
  }: ContainerProps = $props();

  const cls = $derived(containerClasses({ className }));
  const resolvedTagValue = $derived(resolveTag(tag, "div", TagGroup.Container));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
