<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Separator renders hr with optional decorative semantics.
-->
<script lang="ts" module>
  import type { SeparatorOrientation, SeparatorVariant } from "./separator.shared";

  export type SeparatorProps = {
    variant?: SeparatorVariant;
    orientation?: SeparatorOrientation;
    decorative?: boolean;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { separatorClasses } from "./separator.shared";
  import { eqStr } from "../../utils/expr";

  let {
    variant,
    orientation,
    decorative,
    class: className,
    ...rest
  }: SeparatorProps = $props();

  const cls = $derived(separatorClasses({ variant, orientation, className }));
</script>

<hr {...(cls ? { class: cls } : {})} role={decorative ? "presentation" : undefined} aria-hidden={decorative ? "true" : undefined} aria-orientation={eqStr(orientation, "vertical") ? "vertical" : undefined} {...rest} />
