// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.separator — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import separatorRecipeJson from "./separator.variants.json";

export const separatorRecipe = separatorRecipeJson;

export type SeparatorVariant = RecipeKey<typeof separatorRecipe, "variant">;
export type SeparatorOrientation = RecipeKey<typeof separatorRecipe, "orientation">;

/** Separator renders hr with optional decorative semantics. */
export type SeparatorBaseProps = {
  variant?: SeparatorVariant;
  orientation?: SeparatorOrientation;
  decorative?: boolean;
};

export type SeparatorClassesInput = {
  variant?: SeparatorVariant;
  orientation?: SeparatorOrientation;
  className?: string;
};

/** Compose Separator classes without rendering — the cross-runtime `asChild` substitute. */
export function separatorClasses(input: SeparatorClassesInput = {}): string {
  return cn(composeRecipe(separatorRecipe, { variant: input.variant, orientation: input.orientation }), input.className);
}
