// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.title — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import titleRecipeJson from "./title.variants.json";

export const titleRecipe = titleRecipeJson;

/** Title renders the resolved heading element. */
export type TitleBaseProps = {
  as?: 1 | 2 | 3 | 4 | 5 | 6;
};

export type TitleClassesInput = {
  className?: string;
};

/** Compose Title classes without rendering — the cross-runtime `asChild` substitute. */
export function titleClasses(input: TitleClassesInput = {}): string {
  return cn(composeRecipe(titleRecipe, {  }), input.className);
}
