<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Title renders the resolved heading element.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type TitleProps = {
    as?: 1 | 2 | 3 | 4 | 5 | 6;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { titleClasses } from "./title.shared";
  import { titleTag } from "../../utils/expr";

  let {
    as,
    class: className,
    children,
    ...rest
  }: TitleProps = $props();

  const cls = $derived(titleClasses({ className }));
  const resolvedTagValue = $derived(titleTag(as));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
