// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.grid — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import { defaultIfEmpty, intMapOr, mapOr } from "../../utils/expr";
import gridRecipeJson from "./grid.variants.json";

export const gridRecipe = gridRecipeJson;

/** Grid renders a display:grid container. */
export type GridBaseProps = {
  cols?: string;
};

export type GridClassesInput = {
  cols?: string;
  className?: string;
};

/** Compose Grid classes without rendering — the cross-runtime `asChild` substitute. */
export function gridClasses(input: GridClassesInput = {}): string {
  return cn(composeRecipe(gridRecipe, {  }), ((input.className ?? "").includes("grid-cols-") ? "" : mapOr(defaultIfEmpty(input.cols, "1"), { "1": "grid-cols-1", "2": "grid-cols-2", "3": "grid-cols-3", "4": "grid-cols-4", "5": "grid-cols-5", "6": "grid-cols-6", "7": "grid-cols-7", "8": "grid-cols-8", "9": "grid-cols-9", "10": "grid-cols-10", "11": "grid-cols-11", "12": "grid-cols-12", "1-2": "grid-cols-1 md:grid-cols-2", "1-3": "grid-cols-1 md:grid-cols-2 xl:grid-cols-3", "1-4": "grid-cols-1 md:grid-cols-2 xl:grid-cols-4" }, "")), input.className);
}

/** GridCol renders one grid column child. */
export type GridColBaseProps = {
  span?: number;
  start?: number;
  end?: number;
  order?: number;
};

export type GridColClassesInput = {
  span?: number;
  start?: number;
  end?: number;
  order?: number;
  className?: string;
};

/** Compose GridCol classes without rendering — the cross-runtime `asChild` substitute. */
export function gridColClasses(input: GridColClassesInput = {}): string {
  return cn(intMapOr(input.span, { 1: "col-span-1", 2: "col-span-2", 3: "col-span-3", 4: "col-span-4", 5: "col-span-5", 6: "col-span-6", 7: "col-span-7", 8: "col-span-8", 9: "col-span-9", 10: "col-span-10", 11: "col-span-11", 12: "col-span-12" }, ""), intMapOr(input.start, { 1: "col-start-1", 2: "col-start-2", 3: "col-start-3", 4: "col-start-4", 5: "col-start-5", 6: "col-start-6", 7: "col-start-7", 8: "col-start-8", 9: "col-start-9", 10: "col-start-10", 11: "col-start-11", 12: "col-start-12" }, ""), intMapOr(input.end, { 1: "col-end-1", 2: "col-end-2", 3: "col-end-3", 4: "col-end-4", 5: "col-end-5", 6: "col-end-6", 7: "col-end-7", 8: "col-end-8", 9: "col-end-9", 10: "col-end-10", 11: "col-end-11", 12: "col-end-12" }, ""), intMapOr(input.order, { 1: "order-1", 2: "order-2", 3: "order-3", 4: "order-4", 5: "order-5", 6: "order-6", 7: "order-7", 8: "order-8", 9: "order-9", 10: "order-10", 11: "order-11", 12: "order-12" }, ""), input.className);
}
