<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  GridCol renders one grid column child.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type GridColProps = {
    span?: number;
    start?: number;
    end?: number;
    order?: number;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { gridColClasses } from "./grid.shared";

  let {
    span,
    start,
    end,
    order,
    class: className,
    children,
    ...rest
  }: GridColProps = $props();

  const cls = $derived(gridColClasses({ span, start, end, order, className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
