<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Grid renders a display:grid container.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type GridProps = {
    cols?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { gridClasses } from "./grid.shared";

  let {
    cols,
    class: className,
    children,
    ...rest
  }: GridProps = $props();

  const cls = $derived(gridClasses({ cols, className }));
</script>

<div {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</div>
