// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.image — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe, type RecipeKey } from "../../utils";
import imageRecipeJson from "./image.variants.json";

export const imageRecipe = imageRecipeJson;

export type ImageVariant = RecipeKey<typeof imageRecipe, "variant">;
export type ImageSize = RecipeKey<typeof imageRecipe, "size">;
export type ImageFit = RecipeKey<typeof imageRecipe, "fit">;
export type ImagePosition = RecipeKey<typeof imageRecipe, "position">;
export type ImageAspect = RecipeKey<typeof imageRecipe, "aspect">;

/** Image renders an accessible img element. */
export type ImageBaseProps = {
  variant?: ImageVariant;
  size?: ImageSize;
  alt?: string;
  fit?: ImageFit;
  position?: ImagePosition;
  aspect?: ImageAspect;
  loading?: string;
  decoding?: string;
  decorative?: boolean;
};

export type ImageClassesInput = {
  variant?: ImageVariant;
  size?: ImageSize;
  fit?: ImageFit;
  position?: ImagePosition;
  aspect?: ImageAspect;
  className?: string;
};

/** Compose Image classes without rendering — the cross-runtime `asChild` substitute. */
export function imageClasses(input: ImageClassesInput = {}): string {
  return cn(composeRecipe(imageRecipe, { variant: input.variant, size: input.size, fit: input.fit, position: input.position, aspect: input.aspect }), input.className);
}

/** Picture renders a responsive image wrapper. */
export type PictureBaseProps = {

};

export type PictureClassesInput = {
  className?: string;
};

/** Compose Picture classes without rendering — the cross-runtime `asChild` substitute. */
export function pictureClasses(input: PictureClassesInput = {}): string {
  return cn(input.className);
}

/** Source renders a source candidate for picture, video, or audio. */
export type SourceBaseProps = {

};
