<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Image renders an accessible img element.
-->
<script lang="ts" module>
  import type { ImageAspect, ImageFit, ImagePosition, ImageSize, ImageVariant } from "./image.shared";

  export type ImageProps = {
    variant?: ImageVariant;
    size?: ImageSize;
    alt?: string;
    fit?: ImageFit;
    position?: ImagePosition;
    aspect?: ImageAspect;
    loading?: string;
    decoding?: string;
    decorative?: boolean;
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { imageClasses } from "./image.shared";
  import { oneOfOr } from "../../utils/expr";

  let {
    variant,
    size,
    alt,
    fit,
    position,
    aspect,
    loading,
    decoding,
    decorative,
    class: className,
    ...rest
  }: ImageProps = $props();

  const cls = $derived(imageClasses({ variant, size, fit, position, aspect, className }));
</script>

<img alt={((decorative ? "" : alt)) ?? ""} loading={oneOfOr(loading, "lazy", "eager")} decoding={oneOfOr(decoding, "async", "sync", "auto")} {...(cls ? { class: cls } : {})} aria-hidden={decorative ? "true" : undefined} {...rest} />
