<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Picture renders a responsive image wrapper.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type PictureProps = {
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { pictureClasses } from "./image.shared";

  let {
    class: className,
    children,
    ...rest
  }: PictureProps = $props();

  const cls = $derived(pictureClasses({ className }));
</script>

<picture {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</picture>
