<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Source renders a source candidate for picture, video, or audio.
-->
<script lang="ts" module>

  export type SourceProps = {
    class?: string;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  let {
    class: className,
    ...rest
  }: SourceProps = $props();
</script>

<source {...rest} />
