<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Group renders a horizontal flex container.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type GroupProps = {
    tag?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { groupClasses } from "./group.shared";
  import { resolveTag, TagGroup } from "../../utils/tags";

  let {
    tag,
    class: className,
    children,
    ...rest
  }: GroupProps = $props();

  const cls = $derived(groupClasses({ className }));
  const resolvedTagValue = $derived(resolveTag(tag, "div", TagGroup.Group));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
