// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.group — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import groupRecipeJson from "./group.variants.json";

export const groupRecipe = groupRecipeJson;

/** Group renders a horizontal flex container. */
export type GroupBaseProps = {
  tag?: string;
};

export type GroupClassesInput = {
  className?: string;
};

/** Compose Group classes without rendering — the cross-runtime `asChild` substitute. */
export function groupClasses(input: GroupClassesInput = {}): string {
  return cn(composeRecipe(groupRecipe, {  }), input.className);
}
