<!-- Code generated by @ui8kit/codegen. DO NOT EDIT. -->
<!--
  Block renders a resolved landmark element with children.
-->
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export type BlockProps = {
    tag?: string;
    class?: string;
    children?: Snippet;
    [key: string]: unknown;
  };
</script>

<script lang="ts">
  import { blockClasses } from "./block.shared";
  import { resolveTag, TagGroup } from "../../utils/tags";

  let {
    tag,
    class: className,
    children,
    ...rest
  }: BlockProps = $props();

  const cls = $derived(blockClasses({ className }));
  const resolvedTagValue = $derived(resolveTag(tag, "div", TagGroup.Layout));
</script>

<svelte:element this={resolvedTagValue} {...(cls ? { class: cls } : {})} {...rest}>
  {@render children?.()}
</svelte:element>
