// Code generated by @ui8kit/codegen. DO NOT EDIT.
// ui.block — shared TypeScript contract (types + classes helpers)

import { cn, composeRecipe } from "../../utils";
import blockRecipeJson from "./block.variants.json";

export const blockRecipe = blockRecipeJson;

/** Block renders a resolved landmark element with children. */
export type BlockBaseProps = {
  tag?: string;
};

export type BlockClassesInput = {
  className?: string;
};

/** Compose Block classes without rendering — the cross-runtime `asChild` substitute. */
export function blockClasses(input: BlockClassesInput = {}): string {
  return cn(composeRecipe(blockRecipe, {  }), input.className);
}
